// flow-typed signature: 7068e1c6a9c59465853e795f8353e010
// flow-typed version: <<STUB>>/jsx-test-helpers_v^1.1.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsx-test-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsx-test-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsx-test-helpers/lib/index' {
  declare module.exports: any;
}

declare module 'jsx-test-helpers/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsx-test-helpers/lib/index.js' {
  declare module.exports: $Exports<'jsx-test-helpers/lib/index'>;
}
declare module 'jsx-test-helpers/src/index.js' {
  declare module.exports: $Exports<'jsx-test-helpers/src/index'>;
}
