export const CHANGE_MODE = 'CHANGE_MODE';
export const START_PRACTICE = 'START_PRACTICE';
export const MARK_PRACTICE_ANSWER = 'MARK_PRACTICE_ANSWER';
export const MARK_CHALLENGE_ANSWER = 'MARK_CHALLENGE_ANSWER';
export const START_CHALLENGE = 'START_CHALLENGE;';
export const TIMER_TICK = 'TIMER_TICK';
export const TOGGLE_TIMER = 'TOGGLE_TIMER';
